mpi:
  - mpich    # [not win]
  - openmpi  # [not win]
  - msmpi    # [win]

pin_run_as_build:
  mpich:
    max_pin: x.x
    min_pin: x.x
  openmpi:
    max_pin: x.x
    min_pin: x.x
  msmpi:
    max_pin: x.x
    min_pin: x.x
