mpi:
  - mpich    # [not win]
  - openmpi  # [not win]
  - impi     # [not osx and x86_64]
  - msmpi    # [win]
mpich:        # [not win]
  - '3'       # [not win]
extend_keys:  # [not win]
  - mpich     # [not win]
