mpi:
  - mpich    # [not win]
  - mpich    # [not win]
  - openmpi  # [not win]
  - impi     # [not osx and x86_64]
  - msmpi    # [win]
mpich:
  - '3'       # [not win]
  - '4'       # [not win]
  - null      # [not win]
  - null      # [not osx and x86_64]
  - null      # [win]  
zip_keys:
  - - mpi
    - mpich
