{% set version = "3.1.4" %}
{% set mpi = mpi or 'mpich' %}

package:
  name: mpi4py
  version: {{ version }}

source:
  - fn: mpi4py-{{ version }}.tar.gz
    url: https://github.com/mpi4py/mpi4py/releases/download/{{ version }}/mpi4py-{{ version }}.tar.gz
    sha256: 17858f2ebc623220d0120d1fa8d428d033dde749c4bc35b33d81a66ad7f93480

build:
  number: 2
  script:
    - {{ PYTHON }} conf/cythonize.py
    - export OPAL_PREFIX=$PREFIX   # [mpi == "openmpi"]

    # On Windows, we could also just do this:
    #- set CCP_HOME=%LIBRARY_PREFIX%  # [win]
    # but conda-forge/msmpi-feedstock#1 already sets MSMPI_INC and MSMPI_LIB64,
    # so we just use them

    - {{ PYTHON }} -m pip install --no-deps . -vv
    # rewrite references to build prefix as host prefix
    # only affects cross-compiled openmpi
    - sed -i "s@${BUILD_PREFIX}@${PREFIX}@g" "${SP_DIR}/mpi4py/mpi.cfg"  # [build_platform != target_platform]
  skip: true  # [win32]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ mpi }}                              # [build_platform != target_platform and mpi == "openmpi"]
  host:
    - python
    - pip
    - cython <3
    - {{ mpi | replace('impi', 'impi-devel') }}
  run:
    - python
    - {{ mpi | replace('impi', 'impi_rt') }}


about:
  home: https://mpi4py.github.io/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python bindings for MPI
  description: |
    MPI for Python provides bindings of the Message Passing Interface (MPI)
    standard for the Python programming language, allowing any Python program
    to exploit multiple processors.
  doc_url: https://mpi4py.readthedocs.org/
  dev_url: https://github.com/mpi4py/mpi4py

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - msarahan
    - ocefpaf
    - davidbrochart
    - SylvainCorlay
    - leofang
