{% set version = '3.0.3' %}
{% set mpi = mpi or 'mpich' %}

package:
  name: mpi4py
  version: {{ version }}

source:
  fn: mpi4py-{{ version }}.tar.gz
  url: https://github.com/mpi4py/mpi4py/releases/download/{{ version }}/mpi4py-{{ version }}.tar.gz
  sha256: 012d716c8b9ed1e513fcc4b18e5af16a8791f51e6d1716baccf988ad355c5a1f

build:
  number: 4
  script:
    - export OPAL_PREFIX=$PREFIX   # [mpi == "openmpi"]
    #- set CCP_HOME=%LIBRARY_PREFIX%  # [win]

    #- set MSMPI_INC=%LIBRARY_INC%     # [win]
    #- set MSMPI_LIB64=%LIBRARY_LIB%   # [win]

    - dir C:\"Program Files"\"Microsoft MPI"\  # [win]
    - set MSMPI_INC="C:\Program Files\Microsoft MPI\include"  # [win]
    - set MSMPI_LIB64="C:\Program Files\Microsoft MPI\lib"    # [win]
    - {{ PYTHON }} -m pip install --no-deps . -vv
  skip: true  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ mpi }}                              # [build_platform != target_platform and mpi == "openmpi"]
  host:
    - python
    - pip
    - {{ mpi }}
  run:
    - python
    - {{ mpi }}

test:
  commands:
    - |

    {% if mpi == 'openmpi' %}
    - export OMPI_MCA_plm=isolated
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - export OMPI_MCA_rmaps_base_oversubscribe=yes
    - export OMPI_ALLOW_RUN_AS_ROOT=1
    - export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    {% endif %}
    {% if mpi == 'msmpi' %}
    - set MSMPI_BIN=%LIBRARY_BIN%
    - set MSMPI_INC=%LIBRARY_INC%
    - set MSMPI_LIB64=%LIBRARY_LIB%
    {% endif %}

    - python -c "import mpi4py"
    - python -c "import mpi4py.MPI"
    - python -c "import mpi4py.futures"
    - mpiexec -n 2 python -m mpi4py.bench helloworld  # [not win]
    - mpiexec -n 2 python -m mpi4py.bench ringtest    # [not win]
    - mpiexec -help                                        # [win]
    - mpiexec -d 3 -n 2 python -m mpi4py.bench helloworld  # [win]
    - mpiexec -d 3 -n 2 python -m mpi4py.bench ringtest    # [win]

about:
  home: https://mpi4py.github.io/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python bindings for MPI
  description: |
     MPI for Python provides bindings of the Message Passing Interface (MPI)
     standard for the Python programming language, allowing any Python program
     to exploit multiple processors.
  doc_url: https://mpi4py.readthedocs.org/
  dev_url: https://github.com/mpi4py/mpi4py

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - msarahan
    - ocefpaf
    - davidbrochart
    - SylvainCorlay
    - leofang
