{% set version = "4.0.3" %}
{% set mpi = mpi or 'mpich' %}

package:
  name: mpi4py
  version: {{ version }}

source:
  - fn: mpi4py-{{ version }}.tar.gz
    url: https://github.com/mpi4py/mpi4py/releases/download/{{ version }}/mpi4py-{{ version }}.tar.gz
    sha256: de2710d73e25e115865a3ab63d34a54b2d8608b724f761c567b6ad58dd475609

build:
  number: 1
  script:
    - del src\\mpi.pth"  # [win]
    - export I_MPI_CC=$CC  # [mpi == "impi"]
    - {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  {% if mpi == "mpich" and mpich == "3" and py < 312 %}
  skip: true
  {% endif %}
  run_exports:
    - {{ pin_subpackage("mpi4py", max_pin="x") }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ mpi }}                              # [build_platform != target_platform and mpi == "openmpi"]
  host:
    - python
    - pip
    - setuptools
    - python-build
    - cython
    - {{ mpi | replace('impi', 'impi-devel') }}
  run:
    - python
    - {{ mpi | replace('impi', 'impi_rt') }}

test:
  imports:
    - mpi4py
    - mpi4py.MPI
    - mpi4py.futures
    - mpi4py.util.dtlib
    - mpi4py.util.pkl5
    - mpi4py.util.pool
    - mpi4py.util.sync

about:
  home: https://mpi4py.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python bindings for MPI
  description: |
    MPI for Python provides bindings of the Message Passing Interface (MPI)
    standard for the Python programming language, allowing any Python program
    to exploit multiple processors.
  doc_url: https://mpi4py.readthedocs.org/
  dev_url: https://github.com/mpi4py/mpi4py

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - msarahan
    - ocefpaf
    - davidbrochart
    - SylvainCorlay
    - leofang
    - beckermr
