{% set version = "2.0.0" %}
{% set mpi = os.environ.get('MPI_VARIANT', 'mpich') %}
{% set build = 3 %}
package:
  name: mpi4py
  version: {{ version }}

source:
  fn: mpi4py-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/m/mpi4py/mpi4py-{{ version }}.tar.gz
  md5: 4f7d8126d7367c239fd67615680990e3

build:
  number: {{ build }}
  script: pip install --no-deps .
  # TODO: build with msmpi when it works
  skip: true  # [win]
  features:
    - mpi_{{ mpi }}

requirements:
  build:
    - toolchain
    - python
    - pip
    - {{ mpi }}
  run:
    - python
    - {{ mpi }}

test:
  imports:
    - mpi4py
    - mpi4py.MPI

about:
  home: http://pythonhosted.org/mpi4py/
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Provides bindings of the MPI standard for Python
  description: |
     MPI for Python provides bindings of the Message Passing Interface (MPI)
     standard for the Python programming language, allowing any Python program
     to exploit multiple processors.
  doc_url: http://mpi4py.readthedocs.org/
  dev_url: https://bitbucket.org/mpi4py/mpi4py

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - msarahan
    - ocefpaf
