{% set version = '3.0.3' %}
{% set mpi = mpi or 'mpich' %}

package:
  name: mpi4py
  version: {{ version }}

source:
  fn: mpi4py-{{ version }}.tar.gz
  url: https://github.com/mpi4py/mpi4py/releases/download/{{ version }}/mpi4py-{{ version }}.tar.gz
  sha256: 012d716c8b9ed1e513fcc4b18e5af16a8791f51e6d1716baccf988ad355c5a1f

build:
  number: 4
  script:
    - export OPAL_PREFIX=$PREFIX   # [mpi == "openmpi"]
    - {{ PYTHON }} -m pip install --no-deps . -vv  # [not win]
    - {{ PYTHON }} setup.py build -vv              # [win]
    - {{ PYTHON }} setup.py install --user -vv     # [win]
  skip: true  # [win32]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ mpi }}                              # [build_platform != target_platform and mpi == "openmpi"]
  host:
    - python
    - pip
    - {{ mpi }}
  run:
    - python
    - {{ mpi }}

test:
  imports:
    - mpi4py          # [win]
    - mpi4py.MPI      # [win]
    - mpi4py.futures  # [win]

about:
  home: https://mpi4py.github.io/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python bindings for MPI
  description: |
     MPI for Python provides bindings of the Message Passing Interface (MPI)
     standard for the Python programming language, allowing any Python program
     to exploit multiple processors.
  doc_url: https://mpi4py.readthedocs.org/
  dev_url: https://github.com/mpi4py/mpi4py

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - msarahan
    - ocefpaf
    - davidbrochart
    - SylvainCorlay
    - leofang
