schema_version: 1

context:
  version: "4.1.0"
  mpi: ${{ mpi | default('mpich') }}
  python: ${{ python | default("3.10") }}
  build: 3
  build_abi3: ${{ is_abi3 and match(python, "3.10.*") }}
  abi3_tag: "cp3${{ (python | split('.'))[1] }}"
  skip_abi3: ${{ is_abi3 and match(python, ">=3.11") }}

package:
  name: mpi4py
  version: ${{ version }}

source:
  url: https://github.com/mpi4py/mpi4py/releases/download/${{ version }}/mpi4py-${{ version }}.tar.gz
  sha256: 817492796bce771ccd809a6051cf68d48689815493b567a696ce7679260449cd

build:
  # build offset to be preferred over mpich 3 builds
  number: ${{ build + 100 }}
  python:
    version_independent: ${{ build_abi3 }}
  skip: skip_abi3
  script:
    content:
      - if: win
        then: del src\\mpi.pth
      - if: mpi == "impi" and not win
        then: export I_MPI_CC=$CC
      - ${{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
    env:
      MPI4PY_BUILD_PYSABI: ${{ abi3_tag if build_abi3 else "" }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - if: build_platform != target_platform
      then:
        - python
        - cython
        - cross-python_${{ target_platform }}
        - if: mpi == "openmpi"
          then: openmpi
  host:
    - python
    - pip
    - setuptools
    - python-build
    - cython
    - if: mpi == "impi"
      then: impi-devel
      else: ${{ mpi }}
    - if: build_abi3
      then: python-abi3
  run:
    - python
    # only msmpi lacks run_exports
    - if: mpi == "msmpi"
      then: ${{ pin_compatible("msmpi") }}
  run_exports:
    - ${{ pin_subpackage("mpi4py", upper_bound="x") }}

tests:
  - python:
      imports:
        - mpi4py
        - mpi4py.MPI
        - mpi4py.futures
        - mpi4py.util.dtlib
        - mpi4py.util.pkl5
        - mpi4py.util.pool
        - mpi4py.util.sync
      python_version:
        - if: build_abi3
          then:
            - "3.10.*"
            - "3.11.*"
            - "3.12.*"
            - "3.13.*"
            # - "3.14"
  - script:
      content:
        - mpiexec -n 1 python -m mpi4py --version
        - mpiexec -n 1 python -m mpi4py --mpi-std-version
        - mpiexec -n 1 python -m mpi4py --mpi-lib-version
        - mpiexec -n 2 python -m mpi4py.bench helloworld
        - mpiexec -n 2 python -m mpi4py.bench ringtest
        - mpiexec -n 4 python -m mpi4py.bench ringtest -n 1000 -l 100000 -s 100
        # Additional tests are in Python
        - python test_mpi4py.py
      env:
        # workaround https://github.com/prefix-dev/rattler-build/issues/1317
        CONDA_BUILD: "1"
    files:
      recipe:
        - test_mpi4py.py
    requirements:
      run:
        # first test with build Python
        # abi3 build will run with latest, otherwise
        - if: build_abi3
          then: python ${{ python }}
          
  
  - if: build_abi3
    then:
      # abi3audit for 3.10 fails because some stable APIs are backported from Python 3.13 in pyapicompat.h
      - if: not win
        then:
          - script:
              - abi3audit  $PREFIX/lib/python3.13/site-packages/mpi4py/*.so -v -s --assume-minimum-abi3 3.13
            requirements:
              run:
                - abi3audit
                - python 3.13.*
      
      # directly test stable abi against other versions
      - script:
          content:
            - mpiexec -n 2 python -m mpi4py.bench helloworld
            - mpiexec -n 2 python -m mpi4py.bench ringtest -n 1000 -l 100000 -s 100
          env:
            CONDA_BUILD: "1"
        requirements:
          run:
            - python 3.13.*

about:
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: Python bindings for MPI
  description: |
    MPI for Python provides bindings of the Message Passing Interface (MPI)
    standard for the Python programming language, allowing any Python program
    to exploit multiple processors.
  homepage: https://mpi4py.github.io/
  repository: https://github.com/mpi4py/mpi4py
  documentation: https://mpi4py.readthedocs.org/

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - msarahan
    - ocefpaf
    - davidbrochart
    - SylvainCorlay
    - leofang
