schema_version: 1

context:
  version: "4.1.1"
  mpi: ${{ mpi | default('mpich') }}
  build: 3
  # we use the broader ABI compat in mpi4py that allows versions built
  # with latest mpi to be used with earlier versions.
  # these versions of the mpis are the minimum versions we
  # allow and roughly match those in the CI testing for mpi4py.
  # we use the minimum versions on conda-forge in some cases.
  # see https://github.com/conda-forge/mpi4py-feedstock/pull/97#issuecomment-3575450098
  # and https://github.com/conda-forge/mpi4py-feedstock/pull/97#issuecomment-3574064151
  # for details.
  min_mpich: "3.4"
  min_openmpi: "4.1"
  min_impi: "2021.10"
  min_msmpi: "10.1.1"

package:
  name: mpi4py
  version: ${{ version }}

source:
  url: https://github.com/mpi4py/mpi4py/releases/download/${{ version }}/mpi4py-${{ version }}.tar.gz
  sha256: eb2c8489bdbc47fdc6b26ca7576e927a11b070b6de196a443132766b3d0a2a22
  patches:
    - impi202116-win.patch

build:
  # build offset to be preferred over mpich 3 builds
  number: ${{ build + 100 }}
  script:
    - if: win
      then:
        - del src\\mpi.pth
        - set "MPI4PY_BUILD_MPIABI=1"
      else:
        - if: mpi == "impi"
          then: export I_MPI_CC=$CC
        - export MPI4PY_BUILD_MPIABI=1
    - ${{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - if: build_platform != target_platform
      then:
        - python
        - cython
        - cross-python_${{ target_platform }}
        - if: mpi == "openmpi"
          then: openmpi
  host:
    - python
    - pip
    - setuptools
    - python-build
    - cython
    - if: mpi == "impi"
      then: impi-devel
      else: ${{ mpi }}
  run:
    - python
    # we use the broader ABI compat in mpi4py that allows versions built
    # with latest mpi to be used with earlier versions.
    # thus we handle our own run exports and ignore those from the packages.
    - if: mpi == "mpich"
      then: mpich >=${{ min_mpich }}
    - if: mpi == "openmpi"
      then: openmpi >=${{ min_openmpi }}
    - if: mpi == "impi"
      then: impi_rt >=${{ min_impi }}
    - if: mpi == "msmpi"
      then: msmpi >=${{ min_msmpi }}
  ignore_run_exports:
    from_package:
      - if: mpi == "impi"
        then: impi-devel
        else: ${{ mpi }}
  run_exports:
    - ${{ pin_subpackage("mpi4py", upper_bound="x") }}

tests:
  - python:
      imports:
        - mpi4py
        - mpi4py.MPI
        - mpi4py.futures
        - mpi4py.util.dtlib
        - mpi4py.util.pkl5
        - mpi4py.util.pool
        - mpi4py.util.sync
  - script:
      content:
        - mpiexec -n 1 python -m mpi4py --version
        - mpiexec -n 1 python -m mpi4py --mpi-library
        - mpiexec -n 1 python -m mpi4py --mpi-std-version
        - mpiexec -n 1 python -m mpi4py --mpi-lib-version
        - mpiexec -n 2 python -m mpi4py.bench helloworld
        - mpiexec -n 2 python -m mpi4py.bench ringtest
        # Additional tests are in Python
        - python test_mpi4py.py
    files:
      recipe:
        - test_mpi4py.py
  # smoke tests for running against older versions of mpich/openmpi
  - script:
      content:
        - if: mpi == "openmpi"
          then:
            - export OMPI_MCA_plm_rsh_agent=false
            - export OMPI_MCA_rmaps_base_oversubscribe=true
        - mpiexec -n 1 python -m mpi4py --version
        - mpiexec -n 1 python -m mpi4py --mpi-library
        - mpiexec -n 1 python -m mpi4py --mpi-std-version
        - mpiexec -n 1 python -m mpi4py --mpi-lib-version
        - mpiexec -n 2 python -m mpi4py.bench helloworld
        - mpiexec -n 2 python -m mpi4py.bench ringtest
        # Additional tests are in Python
        - python test_mpi4py.py
    files:
      recipe:
        - test_mpi4py.py
    requirements:
      run:
        - if: mpi == "mpich"
          then: mpich =${{ min_mpich }}
        - if: mpi == "openmpi"
          then: openmpi =${{ min_openmpi }}
        - if: mpi == "impi"
          then: impi_rt =${{ min_impi }}
        - if: mpi == "msmpi"
          then: msmpi =${{ min_msmpi }}

about:
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: Python bindings for MPI
  description: |
    MPI for Python provides bindings of the Message Passing Interface (MPI)
    standard for the Python programming language, allowing any Python program
    to exploit multiple processors.
  homepage: https://mpi4py.github.io/
  repository: https://github.com/mpi4py/mpi4py
  documentation: https://mpi4py.readthedocs.org/

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - msarahan
    - ocefpaf
    - davidbrochart
    - SylvainCorlay
    - leofang
