schema_version: 1

context:
  version: "4.1.0"
  mpi: ${{ mpi | default('mpich') }}
  build: 3

package:
  name: mpi4py
  version: ${{ version }}

source:
  url: https://github.com/mpi4py/mpi4py/releases/download/${{ version }}/mpi4py-${{ version }}.tar.gz
  sha256: 817492796bce771ccd809a6051cf68d48689815493b567a696ce7679260449cd
  patches:
    - impi202116-win.patch

build:
  # build offset to be preferred over mpich 3 builds
  number: ${{ build + 100 }}
  script:
    - if: win
      then: del src\\mpi.pth
    - if: mpi == "impi" and not win
      then: export I_MPI_CC=$CC
    - ${{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - if: build_platform != target_platform
      then:
        - python
        - cython
        - cross-python_${{ target_platform }}
        - if: mpi == "openmpi"
          then: openmpi
  host:
    - python
    - pip
    - setuptools
    - python-build
    - cython
    - if: mpi == "impi"
      then: impi-devel
      else: ${{ mpi }}
  run:
    - python
    # only msmpi lacks run_exports
    - if: mpi == "msmpi"
      then: ${{ pin_compatible("msmpi") }}
  run_exports:
    - ${{ pin_subpackage("mpi4py", upper_bound="x") }}

tests:
  - python:
      imports:
        - mpi4py
        - mpi4py.MPI
        - mpi4py.futures
        - mpi4py.util.dtlib
        - mpi4py.util.pkl5
        - mpi4py.util.pool
        - mpi4py.util.sync
  - script:
      content:
        - mpiexec -n 1 python -m mpi4py --version
        - mpiexec -n 1 python -m mpi4py --mpi-std-version
        - mpiexec -n 1 python -m mpi4py --mpi-lib-version
        - mpiexec -n 2 python -m mpi4py.bench helloworld
        - mpiexec -n 2 python -m mpi4py.bench ringtest
        # Additional tests are in Python
        - python test_mpi4py.py
      env:
        # workaround https://github.com/prefix-dev/rattler-build/issues/1317
        CONDA_BUILD: "1"
    files:
      recipe:
        - test_mpi4py.py

about:
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: Python bindings for MPI
  description: |
    MPI for Python provides bindings of the Message Passing Interface (MPI)
    standard for the Python programming language, allowing any Python program
    to exploit multiple processors.
  homepage: https://mpi4py.github.io/
  repository: https://github.com/mpi4py/mpi4py
  documentation: https://mpi4py.readthedocs.org/

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - msarahan
    - ocefpaf
    - davidbrochart
    - SylvainCorlay
    - leofang
